import eslint from "@eslint/js";
import jsxA11y from "eslint-plugin-jsx-a11y";
import promise from "eslint-plugin-promise";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unicorn from "eslint-plugin-unicorn";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["node_modules/**", "build/**", ".react-router/**"] },

  eslint.configs.recommended,

  // ── Global rules (all JS/TS files) ──────────────────────────────────────
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.es2021 },
      ecmaVersion: "latest",
      sourceType: "module",
    },
    plugins: {
      unicorn,
      promise,
      "simple-import-sort": simpleImportSort,
      react: reactPlugin,
      "react-hooks": reactHooksPlugin,
      "jsx-a11y": jsxA11y,
    },
    settings: {
      react: {
        version: "19",
        formComponents: ["Form"],
        linkComponents: [
          { name: "Link", linkAttribute: "to" },
          { name: "NavLink", linkAttribute: "to" },
        ],
      },
    },
    rules: {
      "for-direction": "error",
      "getter-return": "warn",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["warn", "except-parens"],
      "no-console": "warn",
      "no-constant-condition": "error",
      "no-control-regex": "warn",
      "no-debugger": "warn",
      "no-dupe-args": "error",
      "no-dupe-else-if": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-empty": "warn",
      "no-empty-character-class": "warn",
      "no-ex-assign": "warn",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "warn",
      "no-import-assign": "error",
      "no-inner-declarations": "warn",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "warn",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "warn",
      "no-obj-calls": "error",
      "no-promise-executor-return": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "warn",
      "no-setter-return": "error",
      "no-sparse-arrays": "warn",
      "no-template-curly-in-string": "warn",
      "no-unreachable": "warn",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "warn",
      "no-useless-backreference": "warn",
      "require-atomic-updates": "warn",
      "valid-typeof": "warn",
      "accessor-pairs": "off",
      "array-callback-return": ["error", { checkForEach: true }],
      "block-scoped-var": "off",
      "class-methods-use-this": "off",
      complexity: "off",
      "consistent-return": "off",
      curly: ["warn", "all"],
      "default-case": "error",
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "warn",
      eqeqeq: "warn",
      "guard-for-in": "warn",
      "no-alert": "error",
      "no-caller": "error",
      "no-case-declarations": "warn",
      "no-constructor-return": "error",
      "no-else-return": "warn",
      "no-empty-function": "error",
      "no-empty-pattern": "warn",
      "no-empty-static-block": "warn",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "warn",
      "no-fallthrough": "warn",
      "no-global-assign": "warn",
      "no-implicit-coercion": [
        "warn",
        { boolean: false, number: true, string: true },
      ],
      "no-implicit-globals": "error",
      "no-implied-eval": "error",
      "no-invalid-this": "error",
      "no-labels": "error",
      "no-loop-func": "error",
      "no-multi-assign": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-octal": "warn",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-redeclare": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-unmodified-loop-condition": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      "no-unused-private-class-members": "warn",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "warn",
      "no-useless-return": "warn",
      "no-with": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-regex-literals": "error",
      "require-await": "error",
      "require-unicode-regexp": "error",
      yoda: "warn",
      "no-delete-var": "off",
      "no-restricted-globals": [
        "error",
        "addEventListener",
        "blur",
        "close",
        "closed",
        "confirm",
        "defaultStatus",
        "defaultstatus",
        "event",
        "external",
        "find",
        "focus",
        "frameElement",
        "frames",
        "history",
        "innerHeight",
        "innerWidth",
        "length",
        "location",
        "locationbar",
        "menubar",
        "moveBy",
        "moveTo",
        "name",
        "onblur",
        "onerror",
        "onfocus",
        "onload",
        "onresize",
        "onunload",
        "open",
        "opener",
        "opera",
        "outerHeight",
        "outerWidth",
        "pageXOffset",
        "pageYOffset",
        "parent",
        "print",
        "removeEventListener",
        "resizeBy",
        "resizeTo",
        "screen",
        "screenLeft",
        "screenTop",
        "screenX",
        "screenY",
        "scroll",
        "scrollbars",
        "scrollBy",
        "scrollTo",
        "scrollX",
        "scrollY",
        "self",
        "status",
        "statusbar",
        "stop",
        "toolbar",
        "top",
      ],
      "no-shadow-restricted-names": "error",
      "no-undef": "error",
      "no-undef-init": "warn",
      "no-unused-vars": ["warn", { args: "none", ignoreRestSiblings: true }],
      "no-use-before-define": [
        "warn",
        { classes: false, functions: false, variables: false },
      ],
      "func-names": ["warn", "as-needed"],
      "new-cap": "warn",
      "no-array-constructor": "error",
      "no-bitwise": "warn",
      "no-multi-assign": "error",
      "no-new-object": "error",
      "no-unneeded-ternary": "warn",
      "one-var": ["warn", "never"],
      "operator-assignment": ["warn", "always"],
      "prefer-exponentiation-operator": "warn",
      "prefer-object-has-own": "warn",
      "prefer-object-spread": "warn",
      "spaced-comment": ["warn", "always", {}],
      "constructor-super": "error",
      "no-class-assign": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "warn",
      "no-dupe-class-members": "error",
      "no-this-before-super": "error",
      "no-useless-computed-key": "warn",
      "no-useless-constructor": "warn",
      "no-useless-rename": "warn",
      "no-var": "error",
      "object-shorthand": "warn",
      "prefer-const": "warn",
      "prefer-destructuring": ["warn", { object: true, array: false }],
      "prefer-numeric-literals": "warn",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "warn",
      "require-yield": "error",
      "symbol-description": "error",
      "prefer-arrow-callback": "warn",

      "react/boolean-prop-naming": "off",
      "react/button-has-type": "error",
      "react/default-props-match-prop-types": "off",
      "react/destructuring-assignment": "off",
      "react/display-name": "off",
      "react/forbid-dom-props": "off",
      "react/forbid-elements": "off",
      "react/forbid-foreign-prop-types": ["warn", { allowInPropTypes: true }],
      "react/forbid-prop-types": "off",
      "react/function-component-definition": [
        "warn",
        {
          namedComponents: "function-declaration",
          unnamedComponents: "arrow-function",
        },
      ],
      "react/jsx-boolean-value": "error",
      "react/jsx-curly-brace-presence": [
        "warn",
        { children: "never", props: "never" },
      ],
      "react/jsx-fragments": ["warn", "syntax"],
      "react/jsx-handler-names": [
        "warn",
        {
          checkLocalVariables: false,
          eventHandlerPrefix: "handle",
          eventHandlerPropPrefix: "on",
        },
      ],
      "react/jsx-key": [
        "warn",
        { checkFragmentShorthand: true, checkKeyMustBeforeSpread: true },
      ],
      "react/jsx-no-comment-textnodes": "warn",
      "react/jsx-no-constructed-context-values": "warn",
      "react/jsx-no-duplicate-props": "error",
      "react/jsx-no-script-url": "warn",
      "react/jsx-no-target-blank": "warn",
      "react/jsx-no-useless-fragment": "warn",
      "react/jsx-pascal-case": ["warn", { allowAllCaps: true, ignore: [] }],
      "react/jsx-uses-react": "warn",
      "react/no-array-index-key": "warn",
      "react/no-children-prop": "error",
      "react/no-danger": "warn",
      "react/no-danger-with-children": "error",
      "react/no-deprecated": "error",
      "react/no-did-update-set-state": "warn",
      "react/no-direct-mutation-state": "error",
      "react/no-find-dom-node": "error",
      "react/no-is-mounted": "error",
      "react/no-namespace": "warn",
      "react/no-object-type-as-default-prop": "error",
      "react/no-redundant-should-component-update": "error",
      "react/no-string-refs": "error",
      "react/no-typos": "error",
      "react/no-unknown-property": "warn",
      "react/no-unsafe": "error",
      "react/no-unused-prop-types": "warn",
      "react/no-unused-state": "warn",
      "react/no-will-update-set-state": "warn",
      "react/prefer-es6-class": "error",
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/require-render-return": "error",
      "react/self-closing-comp": "warn",
      "react/static-property-placement": ["error", "static public field"],
      "react/style-prop-object": "warn",
      "react/void-dom-elements-no-children": "error",

      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": [
        "error",
        { components: ["Link", "NavLink"] },
      ],
      "jsx-a11y/anchor-is-valid": [
        "error",
        { aspects: ["invalidHref", "noHref", "preferButton"], components: [] },
      ],
      "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-proptypes": "error",
      "jsx-a11y/aria-role": ["warn", { ignoreNonDOM: true }],
      "jsx-a11y/aria-unsupported-elements": "error",
      "jsx-a11y/autocomplete-valid": "error",
      "jsx-a11y/click-events-have-key-events": "warn",
      "jsx-a11y/control-has-associated-label": "warn",
      "jsx-a11y/heading-has-content": "warn",
      "jsx-a11y/html-has-lang": "warn",
      "jsx-a11y/iframe-has-title": "warn",
      "jsx-a11y/img-redundant-alt": "warn",
      "jsx-a11y/interactive-supports-focus": "error",
      "jsx-a11y/label-has-associated-control": "error",
      "jsx-a11y/lang": "error",
      "jsx-a11y/media-has-caption": "warn",
      "jsx-a11y/mouse-events-have-key-events": "error",
      "jsx-a11y/no-access-key": "warn",
      "jsx-a11y/no-aria-hidden-on-focusable": "error",
      "jsx-a11y/no-autofocus": "error",
      "jsx-a11y/no-distracting-elements": "warn",
      "jsx-a11y/no-interactive-element-to-noninteractive-role": "error",
      "jsx-a11y/no-noninteractive-element-interactions": "error",
      "jsx-a11y/no-noninteractive-element-to-interactive-role": [
        "error",
        {
          li: ["menuitem", "option", "row", "tab", "treeitem"],
          ol: [
            "listbox",
            "menu",
            "menubar",
            "radiogroup",
            "tablist",
            "tree",
            "treegrid",
          ],
          table: ["grid"],
          td: ["gridcell"],
          ul: [
            "listbox",
            "menu",
            "menubar",
            "radiogroup",
            "tablist",
            "tree",
            "treegrid",
          ],
        },
      ],
      "jsx-a11y/no-noninteractive-tabindex": "error",
      "jsx-a11y/no-redundant-roles": "warn",
      "jsx-a11y/no-static-element-interactions": "error",
      "jsx-a11y/prefer-tag-over-role": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",
      "jsx-a11y/scope": "error",
      "jsx-a11y/tabindex-no-positive": "error",

      "react-hooks/exhaustive-deps": "error",
      "react-hooks/rules-of-hooks": "error",

      "promise/no-multiple-resolved": "warn",
      "promise/no-nesting": "warn",
      "promise/no-new-statics": "error",
      "promise/no-promise-in-callback": "warn",
      "promise/no-return-in-finally": "warn",
      "promise/no-return-wrap": "error",
      "promise/param-names": "warn",
      "promise/prefer-await-to-callbacks": "warn",
      "promise/prefer-await-to-then": "warn",

      "simple-import-sort/imports": "warn",
      "simple-import-sort/exports": "warn",

      "unicorn/better-regex": "error",
      "unicorn/catch-error-name": "error",
      "unicorn/consistent-destructuring": "error",
      "unicorn/consistent-function-scoping": "error",
      "unicorn/custom-error-definition": "warn",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/explicit-length-check": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-abusive-eslint-disable": "error",
      "unicorn/no-array-method-this-argument": "warn",
      "unicorn/no-array-push-push": "warn",
      "unicorn/no-await-expression-member": "error",
      "unicorn/no-console-spaces": "error",
      "unicorn/no-document-cookie": "warn",
      "unicorn/no-hex-escape": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-lonely-if": "warn",
      "unicorn/no-negated-condition": "warn",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/no-object-as-default-parameter": "warn",
      "unicorn/no-process-exit": "error",
      "unicorn/no-static-only-class": "error",
      "unicorn/no-thenable": "warn",
      "unicorn/no-this-assignment": "warn",
      "unicorn/no-typeof-undefined": "warn",
      "unicorn/no-unreadable-array-destructuring": "warn",
      "unicorn/no-unreadable-iife": "warn",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-fallback-in-spread": "warn",
      "unicorn/no-useless-promise-resolve-reject": "warn",
      "unicorn/no-useless-spread": "error",
      "unicorn/no-useless-switch-case": "warn",
      "unicorn/no-useless-undefined": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/numeric-separators-style": "warn",
      "unicorn/prefer-add-event-listener": "error",
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-array-flat": "warn",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-index-of": "warn",
      "unicorn/prefer-array-some": "warn",
      "unicorn/prefer-code-point": "warn",
      "unicorn/prefer-date-now": "warn",
      "unicorn/prefer-default-parameters": "warn",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-dataset": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-export-from": "warn",
      "unicorn/prefer-keyboard-event-key": "error",
      "unicorn/prefer-logical-operator-over-ternary": "warn",
      "unicorn/prefer-math-trunc": "warn",
      "unicorn/prefer-modern-dom-apis": "error",
      "unicorn/prefer-modern-math-apis": "warn",
      "unicorn/prefer-native-coercion-functions": "error",
      "unicorn/prefer-negative-index": "error",
      "unicorn/prefer-number-properties": ["warn", { checkInfinity: false }],
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-prototype-methods": "warn",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-set-has": "error",
      "unicorn/prefer-set-size": "warn",
      "unicorn/prefer-spread": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-switch": [
        "error",
        { emptyDefaultCase: "no-default-comment" },
      ],
      "unicorn/prefer-type-error": "error",
      "unicorn/relative-url-style": "warn",
      "unicorn/require-array-join-separator": "warn",
      "unicorn/require-number-to-fixed-digits-argument": "warn",
      "unicorn/string-content": "off",
      "unicorn/switch-case-braces": "warn",
      "unicorn/template-indent": "warn",
      "unicorn/throw-new-error": "error",
    },
  },

  {
    files: ["**/*.ts", "**/*.tsx"],
    plugins: { "@typescript-eslint": tseslint.plugin },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: "./tsconfig.json",
        warnOnUnsupportedTypeScriptVersion: true,
      },
    },
    rules: {
      // Disable base rules superseded by @typescript-eslint equivalents
      "array-callback-return": "off",
      "constructor-super": "off",
      "default-case": "off",
      "default-param-last": "off",
      "dot-notation": "off",
      "getter-return": "off",
      "lines-between-class-members": "off",
      "no-array-constructor": "off",
      "no-const-assign": "off",
      "no-constructor-return": "off",
      "no-dupe-args": "off",
      "no-dupe-class-members": "off",
      "no-dupe-keys": "off",
      "no-empty-function": "off",
      "no-func-assign": "off",
      "no-import-assign": "off",
      "no-invalid-this": "off",
      "no-loop-func": "off",
      "no-loss-of-precision": "off",
      "no-obj-calls": "off",
      "no-redeclare": "off",
      "no-setter-return": "off",
      "no-throw-literal": "off",
      "no-this-before-super": "off",
      "no-unreachable": "off",
      "no-unsafe-negation": "off",
      "no-unsafe-optional-chaining": "off",
      "no-unused-expressions": "off",
      "no-unused-private-class-members": "off",
      "no-unused-vars": "off",
      "no-use-before-define": "off",
      "no-useless-constructor": "off",
      "no-undef": "off",
      "require-await": "off",
      "return-await": "off",
      "valid-typeof": "off",
      "prefer-const": "error",

      // ── @typescript-eslint (v8 compatible) ─────────────────────────────
      "@typescript-eslint/adjacent-overload-signatures": "error",
      "@typescript-eslint/array-type": ["warn", { default: "array" }],
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/ban-ts-comment": [
        "error",
        {
          "ts-expect-error": "allow-with-description",
          "ts-ignore": true,
          "ts-nocheck": true,
        },
      ],
      "@typescript-eslint/class-literal-property-style": "off",
      "@typescript-eslint/consistent-indexed-object-style": "off",
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        { assertionStyle: "as", objectLiteralTypeAssertions: "never" },
      ],
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { disallowTypeAnnotations: true, prefer: "type-imports" },
      ],
      "@typescript-eslint/default-param-last": "error",
      "@typescript-eslint/dot-notation": "error",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-member-accessibility": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/init-declarations": "off",
      "@typescript-eslint/member-ordering": "warn",
      "@typescript-eslint/method-signature-style": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-array-constructor": "error",
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/no-confusing-non-null-assertion": "error",
      "@typescript-eslint/no-confusing-void-expression": "warn",
      "@typescript-eslint/no-default-export": "off",
      "@typescript-eslint/no-dupe-class-members": "error",
      "@typescript-eslint/no-dynamic-delete": "warn",
      "@typescript-eslint/no-empty-function": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-extraneous-class": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-for-in-array": "warn",
      "@typescript-eslint/no-implied-eval": "error",
      "@typescript-eslint/no-inferrable-types": "warn",
      "@typescript-eslint/no-invalid-this": "error",
      "@typescript-eslint/no-invalid-void-type": "error",
      "@typescript-eslint/no-loop-func": "error",
      "@typescript-eslint/no-magic-numbers": "off",
      "@typescript-eslint/no-misused-promises": [
        "warn",
        { checksConditionals: true, checksVoidReturn: true },
      ],
      "@typescript-eslint/no-namespace": "warn",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/no-redeclare": "warn",
      "@typescript-eslint/no-redundant-type-constituents": "warn",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-this-alias": [
        "error",
        { allowDestructuring: true },
      ],

      "@typescript-eslint/no-unnecessary-boolean-literal-compare": [
        "warn",
        {
          allowComparingNullableBooleansToFalse: false,
          allowComparingNullableBooleansToTrue: false,
        },
      ],
      "@typescript-eslint/no-unnecessary-qualifier": "error",
      "@typescript-eslint/no-unnecessary-type-arguments": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "warn",
      "@typescript-eslint/no-unnecessary-type-constraint": "warn",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unused-expressions": "error",
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-use-before-define": "off",
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-useless-empty-export": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/parameter-properties": [
        "warn",
        { prefer: "parameter-property" },
      ],
      "@typescript-eslint/prefer-as-const": "error",
      "@typescript-eslint/prefer-enum-initializers": "error",
      "@typescript-eslint/prefer-for-of": "warn",
      "@typescript-eslint/prefer-includes": "warn",
      "@typescript-eslint/prefer-literal-enum-member": "error",
      "@typescript-eslint/prefer-namespace-keyword": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-regexp-exec": "warn",
      "@typescript-eslint/prefer-string-starts-ends-with": "error",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/require-array-sort-compare": "warn",
      "@typescript-eslint/restrict-plus-operands": "warn",
      "@typescript-eslint/restrict-template-expressions": [
        "warn",
        { allowBoolean: true, allowNumber: true },
      ],
      "@typescript-eslint/return-await": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "warn",
      "@typescript-eslint/triple-slash-reference": "warn",
      "@typescript-eslint/unified-signatures": "warn",
    },
  },

  {
    files: ["app/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "unicorn/prefer-module": "off",
    },
  },

  {
    files: ["**/routes/**/*.{tsx,jsx,ts,js}"],
    rules: {
      "react/display-name": "off",
      "@typescript-eslint/only-throw-error": "off",
    },
  },
);
